name: Deliver App Image
run-name: Deliver image by @${{ github.actor }}

on: workflow_dispatch

env:
  REGISTRY: us-central1-docker.pkg.dev/learn-terraform-364715/docker-images
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/pys:latest

